### PR TITLE
Implement relative pointer protocol

### PR DESCRIPTION
**Pull request by Mic92**
Doesn't work yet. Maybe you can spot the error.

### CODE REVIEW

**Comment by talex5** [comment]
Doesn't work in what way?

**Comment by Mic92** [comment]
I have to check, when I run teeworlds in qemu with the rutuabaga gpu, it doesn't yet forward relative mouse pointer events. How can I spot if an application is picking up on the advertised events?

**Comment by talex5** [comment]
You can run your application with `WAYLAND_DEBUG=1` to see what it's doing. That will show you whether the proxy advertised the extension or not, and whether the application decided to use it. You can also run the proxy with `-v` to see both communications with the application and with the host.

Also: If you're running an unmodified version of the proxy at the same time as your test instance, be sure to use `--virtio-gpu` so that the test instance connects directly to the host, without going via the other proxy. You might want to use `--tag` to check which proxies are being used.

**Comment by Mic92** [comment]
For other reference, I also add to patch [rutabaga-gfx-ffi](https://git.clan.lol/clan/clan-core/src/branch/main/pkgs/rutabaga-gfx-ffi) as otherwise the wayland keyboard buffer was not mmapable.

**Comment by Mic92** [comment]
> You can run your application with `WAYLAND_DEBUG=1` to see what it's doing. That will show you whether the proxy advertised the extension or not, and whether the application decided to use it. You can also run the proxy with `-v` to see both communications with the application and with the host.
> 
> Also: If you're running an unmodified version of the proxy at the same time as your test instance, be sure to use `--virtio-gpu` so that the test instance connects directly to the host, without going via the other proxy. You might want to use `--tag` to check which proxies are being used.

Ok. Will check it out next week.

**Comment by Mic92** [comment]
Ok. I can see those events being forwarded now.

**Comment by Mic92** [comment]
Anything more to do here?

**Comment by Mic92** [comment]
Friendly ping

**Comment by talex5** [comment]
I added ocaml-wayland as a submodule, since the released version doesn't have the new protocol. That should fix it.

**Comment by Mic92** [comment]
Do you plan on publishing a release of ocaml-wayland soonish?

**Pull request merged**
